apiVersion: v1
kind: Pod
metadata:
  name: nginx
spec:
  containers:
  - name: nginx1
    image: nginx:alpine
    resources:
      requests:
        memory: "50Mi"
        cpu: "1000m"
      limits:
        memory: "50Mi"
        cpu: "1000m" 
    ports:
    - containerPort: 80
---
apiVersion: v1
kind: Pod
metadata:
  name: nginx3
spec:
  containers:
  - name: nginx1
    image: nginx:alpine
    ports:
    - containerPort: 80